-- AlterTable
ALTER TABLE "Framework" ALTER COLUMN "name" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Profile" ALTER COLUMN "quote" DROP NOT NULL,
ALTER COLUMN "languages" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "libraries" SET DEFAULT ARRAY[]::TEXT[];

-- AlterTable
ALTER TABLE "Project" ALTER COLUMN "title" DROP NOT NULL,
ALTER COLUMN "context" DROP NOT NULL,
ALTER COLUMN "description" DROP NOT NULL,
ALTER COLUMN "github_link" DROP NOT NULL,
ALTER COLUMN "live_link" DROP NOT NULL,
ALTER COLUMN "api_link" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Skill" ALTER COLUMN "title" DROP NOT NULL,
ALTER COLUMN "content" SET DEFAULT ARRAY[]::TEXT[];
